apiVersion: batch/v1
kind: Job
metadata:
  name: secret-santa-job-{{ id }}
spec:
  template:
    spec:
      containers:
      - name: job
        image: registry.declan.sh/secret-santa-job:1
        env:
        - name: DATA_PATH
          value: /usr/lib/data/data.json
        volumeMounts:
        - mountPath: /usr/lib/data
          name: data
      volumes:
      - name: data
        configMap:
          name: secret-santa-job-{{ id }}
      restartPolicy: Never
  backoffLimit: 4